export default {
  login: 'ورود',
  password: 'رمز عبور',
  phoneNumber: 'شماره تلفن',
  phoneNumberIsRequired: 'شماره تلفن الزامی است',
  passwordIsRequired: 'رمز عبور الزامی است',
  doNotHaveAccount: 'در حال حاضر اکانت ندارید؟',
  haveAccount: 'اکانت دارید؟',
  singUp: 'ثبت نام',
  loginSuccess: 'ورود با موفقت انجام شد',
  firstName: 'نام',
  lastName: 'نام خانوادگی',
  birthDate: 'تاریخ تولد',
  email: 'ایمیل',
  men: 'مرد',
  woman: 'زن',
  real: 'حقیقی',
  legal: 'حقوقی',
  save: 'ذخیره',
  gender: 'جنسیت',
  legality: 'حقیقی/حقوقی',
  logout: 'خروج از حساب کاربری',
  userNameIsRequired: 'نام کاربری الزامی است',
  signUp: 'ثبت نام',
  forgetPassword: 'فراموشی رمز عبور؟',
  profile: 'مشخصات فردی',
  job: 'شغل',
  userName: 'نام کاربری',
  confirmPassword: 'تکرار رمز عبور',
  minLengthMustBeGreaterThanSix: 'باید حداقل بیشتر از 6 کارکتر باشد'
}
